version: "3.7"


services:
  chat_gpt_bot:
    build:
      context: ""
      dockerfile: Dockerfile.chat_bot
    container_name: chat_gpt_bot
    hostname: chat_gpt_bot
    restart: always
    volumes:
      - .:/ProjectChatGPT
    ports:
      - 10000:10000
